/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.GestionAplicacion;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Corredor;
import vista.tableModels.TableModelCorredores;

/**
 *
 * @author Miguel
 */
public class JDCorredores extends javax.swing.JDialog {

    private final GestionAplicacion gestion;

    /**
     * Creates new form JDCorredores
     */
    public JDCorredores(java.awt.Frame parent, boolean modal, GestionAplicacion gestion) {
        super(parent, modal);
        this.gestion = gestion;
        initComponents();
        this.setLocationRelativeTo(null);
        pintarTabla();
        ponLaAyuda();
        jTableCorredores.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (jTableCorredores.getSelectedRow() == -1) {
                    jBModificarCorredor.setEnabled(false);
                    jBEliminarCorredor.setEnabled(false);
                } else {
                    jBEliminarCorredor.setEnabled(true);
                    jBModificarCorredor.setEnabled(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jBInscribirCorredor = new javax.swing.JButton();
        jBguardarCsv = new javax.swing.JButton();
        jBModificarCorredor = new javax.swing.JButton();
        jBEliminarCorredor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCorredores);

        jBInscribirCorredor.setText("Inscribir corredor");
        jBInscribirCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirCorredorActionPerformed(evt);
            }
        });

        jBguardarCsv.setText("Guardar corredores");
        jBguardarCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarCsvActionPerformed(evt);
            }
        });

        jBModificarCorredor.setText("Modificar corredor");
        jBModificarCorredor.setEnabled(false);
        jBModificarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarCorredorActionPerformed(evt);
            }
        });

        jBEliminarCorredor.setText("Eliminar corredor");
        jBEliminarCorredor.setEnabled(false);
        jBEliminarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarCorredorActionPerformed(evt);
            }
        });

        jMenuAyuda.setText("Ayuda");

        jMenuItemAyuda.setText("mostrar ayuda");
        jMenuAyuda.add(jMenuItemAyuda);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBInscribirCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jBModificarCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBguardarCsv, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jBEliminarCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBInscribirCorredor)
                        .addGap(18, 18, 18)
                        .addComponent(jBModificarCorredor)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminarCorredor)
                        .addGap(18, 18, 18)
                        .addComponent(jBguardarCsv)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInscribirCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirCorredorActionPerformed
        JDInscripcionCorredor inscipcion = new JDInscripcionCorredor(this, true, gestion);
        inscipcion.setVisible(true);
        jTableCorredores.setModel(new TableModelCorredores(gestion.getCorredores()));
    }//GEN-LAST:event_jBInscribirCorredorActionPerformed

    private void jBguardarCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarCsvActionPerformed
        gestion.GuardarCsvCorredores();
        JOptionPane.showMessageDialog(this, "Se han guardado los corredores en el CSV");
    }//GEN-LAST:event_jBguardarCsvActionPerformed

    private void jBModificarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarCorredorActionPerformed
        int seleccionado = jTableCorredores.convertRowIndexToModel(jTableCorredores.getSelectedRow());
        Corredor perSeleccionada = gestion.getCorredores().get(seleccionado);
        JDInscripcionCorredor dialogoModificar = new JDInscripcionCorredor(this, true, gestion, perSeleccionada);
        dialogoModificar.setVisible(true);
        jTableCorredores.setModel(new TableModelCorredores(gestion.getCorredores()));
    }//GEN-LAST:event_jBModificarCorredorActionPerformed

    private void jBEliminarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarCorredorActionPerformed
        int seleccionado = jTableCorredores.convertRowIndexToModel(jTableCorredores.getSelectedRow());
        Corredor perSeleccionada = gestion.getCorredores().get(seleccionado);
        gestion.getCorredores().remove(perSeleccionada);
        jTableCorredores.setModel(new TableModelCorredores(gestion.getCorredores()));
    }//GEN-LAST:event_jBEliminarCorredorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminarCorredor;
    private javax.swing.JButton jBInscribirCorredor;
    private javax.swing.JButton jBModificarCorredor;
    private javax.swing.JButton jBguardarCsv;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCorredores;
    // End of variables declaration//GEN-END:variables

    private void pintarTabla() {
        ArrayList<Corredor> listCorredors = gestion.getCorredores();
        TableModelCorredores modelo = new TableModelCorredores(listCorredors);
        jTableCorredores.setModel(modelo);
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(modelo);
        jTableCorredores.setRowSorter(elQueOrdena);

    }
    private void ponLaAyuda() {
        try {
            // Carga el fichero de ayuda
            File fichero = new File("help" + File.separator + "help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // Pone ayuda a item de menu al pulsarlo y a F1 en ventana
            // principal y secundaria.
            hb.enableHelpOnButton(jMenuItemAyuda, "ventana_corredores", helpset);
            hb.enableHelpKey(getRootPane(), "ventana_corredores", helpset);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
