/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.GestionAplicacion;
import java.util.ArrayList;
import modelo.Carrera;
import modelo.CorredorParaCarrera;

/**
 *
 * @author Miguel
 */
public class JDCronometro extends javax.swing.JDialog {

    private final GestionAplicacion gestion;
    private final Carrera carrera;

    public JDCronometro(java.awt.Dialog parent, boolean modal, GestionAplicacion gestion, Carrera carreraSeleccionada) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.gestion = gestion;
        this.carrera = carreraSeleccionada;
        jLNombreCarrera.setText(carrera.getNombre());
        rellenarCombo();
        jTextAreaLog.append("\ndorsal ----- tiempo \n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cronometro1 = new cronometro.Cronometro();
        jLNombreCarrera = new javax.swing.JLabel();
        jComboBoxDorsales = new javax.swing.JComboBox<>();
        jBRegistrarTiempo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLNombreCarrera.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLNombreCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNombreCarrera.setText(org.openide.util.NbBundle.getMessage(JDCronometro.class, "JDCronometro.jLNombreCarrera.text")); // NOI18N

        jBRegistrarTiempo.setText(org.openide.util.NbBundle.getMessage(JDCronometro.class, "JDCronometro.jBRegistrarTiempo.text")); // NOI18N
        jBRegistrarTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarTiempoActionPerformed(evt);
            }
        });

        jTextAreaLog.setEditable(false);
        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jTextAreaLog.setText(org.openide.util.NbBundle.getMessage(JDCronometro.class, "JDCronometro.jTextAreaLog.text")); // NOI18N
        jScrollPane1.setViewportView(jTextAreaLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBoxDorsales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jBRegistrarTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLNombreCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cronometro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cronometro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDorsales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRegistrarTiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarTiempoActionPerformed
        registrarTiempo();
    }//GEN-LAST:event_jBRegistrarTiempoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cronometro.Cronometro cronometro1;
    private javax.swing.JButton jBRegistrarTiempo;
    private javax.swing.JComboBox<String> jComboBoxDorsales;
    private javax.swing.JLabel jLNombreCarrera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables

    private void rellenarCombo() {
        ArrayList<CorredorParaCarrera> corredores = carrera.getCorredores();
        for (CorredorParaCarrera corredor : corredores) {
            jComboBoxDorsales.addItem(String.valueOf(corredor.getDorsal()));
        }
    }

    private boolean registrarTiempo() {
        Object selectedItem = jComboBoxDorsales.getSelectedItem();
        ArrayList<CorredorParaCarrera> corredores = carrera.getCorredores();
        for (CorredorParaCarrera corredor : corredores) {
            if (corredor.getDorsal() == Integer.parseInt((String) selectedItem)) {
                if (corredor.getTiempo().equals("00:00:00")) {
                    corredor.setTiempo(cronometro1.getTiempo());
                    if (corredor.getDorsal() < 10) {
                        jTextAreaLog.append(corredor.getDorsal() + " ------------ " + corredor.getTiempo() + "\n");
                    } else if (corredor.getDorsal() < 100) {
                        jTextAreaLog.append(corredor.getDorsal() + " ----------- " + corredor.getTiempo() + "\n");
                    } else if (corredor.getDorsal() < 1000) {
                        jTextAreaLog.append(corredor.getDorsal() + " ---------- " + corredor.getTiempo() + "\n");
                    } else if (corredor.getDorsal() < 10000) {
                        jTextAreaLog.append(corredor.getDorsal() + " --------- " + corredor.getTiempo() + "\n");
                    } else {
                        jTextAreaLog.append(corredor.getDorsal() + " -------- " + corredor.getTiempo() + "\n");
                    }
                    return true;
                }
            }
        }
        return false;
    }
}
