/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.corredores.vista;

import aplicacion.corredores.vista.tableModels.TableModelCarreras;
import aplicacion.corredores.controlador.GestionAplicacion;
import aplicacion.corredores.modelo.Carrera;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author migue
 */
public class jDCarreras extends javax.swing.JDialog {

    private GestionAplicacion gestion;

    /**
     *
     * @param parent
     * @param modal
     * @param gestion
     */
    public jDCarreras(java.awt.Frame parent, boolean modal, GestionAplicacion gestion) {
        super(parent, modal);
        this.gestion = gestion;
        initComponents();
        jComboBoxTipoCarrear.setSelectedIndex(0);
        pintartabla();
        jTCarreras.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (jTCarreras.getSelectedRow() == -1) {
                    jBEliminarCarrera.setEnabled(false);
                    jBModificarCarrera.setEnabled(false);
                } else {
                    jBEliminarCarrera.setEnabled(true);
                    jBModificarCarrera.setEnabled(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBCrearCarrera = new javax.swing.JButton();
        jBGuardarCarreras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCarreras = new javax.swing.JTable();
        jBModificarCarrera = new javax.swing.JButton();
        jBEliminarCarrera = new javax.swing.JButton();
        jComboBoxTipoCarrear = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion carreras");

        jBCrearCarrera.setText("Crear carrera");
        jBCrearCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearCarreraActionPerformed(evt);
            }
        });

        jBGuardarCarreras.setText("Guardar carreras");
        jBGuardarCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarCarrerasActionPerformed(evt);
            }
        });

        jTCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTCarreras);

        jBModificarCarrera.setText("Modificar carrera");
        jBModificarCarrera.setEnabled(false);
        jBModificarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarCarreraActionPerformed(evt);
            }
        });

        jBEliminarCarrera.setText("Eliminar carrera");
        jBEliminarCarrera.setEnabled(false);
        jBEliminarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarCarreraActionPerformed(evt);
            }
        });

        jComboBoxTipoCarrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Finalizadas", "Pendientes", " " }));
        jComboBoxTipoCarrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoCarrearActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de carrera :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBModificarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jBCrearCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBEliminarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBGuardarCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTipoCarrear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBCrearCarrera)
                        .addGap(18, 18, 18)
                        .addComponent(jBModificarCarrera)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminarCarrera)
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardarCarreras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoCarrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrearCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearCarreraActionPerformed
        JDCreacionCarrera creacion = new JDCreacionCarrera(this, true, gestion);
        creacion.setVisible(true);
        pintartabla();
    }//GEN-LAST:event_jBCrearCarreraActionPerformed

    private void jBGuardarCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarCarrerasActionPerformed
        gestion.GuardarCsvCarreras();
    }//GEN-LAST:event_jBGuardarCarrerasActionPerformed

    private void jBModificarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarCarreraActionPerformed
        int seleccionado = jTCarreras.convertRowIndexToModel(jTCarreras.getSelectedRow());
        Carrera carrera = gestion.getCarreras().get(seleccionado);
        JDCreacionCarrera dialogoModificar = new JDCreacionCarrera(this, true, gestion, carrera);
        dialogoModificar.setVisible(true);
        pintartabla();
    }//GEN-LAST:event_jBModificarCarreraActionPerformed

    private void jBEliminarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarCarreraActionPerformed
        int seleccionado = jTCarreras.convertRowIndexToModel(jTCarreras.getSelectedRow());
        Carrera carreraSeleccionada = gestion.getCarreras().get(seleccionado);
        gestion.getCarreras().remove(carreraSeleccionada);
        pintartabla();
    }//GEN-LAST:event_jBEliminarCarreraActionPerformed

    private void jComboBoxTipoCarrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoCarrearActionPerformed
        pintartabla();
    }//GEN-LAST:event_jComboBoxTipoCarrearActionPerformed

    private void pintartabla() {
        ArrayList<Carrera> listaCarreras;
        if (jComboBoxTipoCarrear.getSelectedIndex() == 0) {
            listaCarreras = gestion.getCarreras();
        } else if (jComboBoxTipoCarrear.getSelectedIndex() == 1) {
            listaCarreras = gestion.getCarrerasFinalizadas();
        } else {
            listaCarreras = gestion.getCarrerasProximas();
        }
        TableModelCarreras modelo = new TableModelCarreras(listaCarreras);
        jTCarreras.setModel(modelo);
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(modelo);
        jTCarreras.setRowSorter(elQueOrdena);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrearCarrera;
    private javax.swing.JButton jBEliminarCarrera;
    private javax.swing.JButton jBGuardarCarreras;
    private javax.swing.JButton jBModificarCarrera;
    private javax.swing.JComboBox<String> jComboBoxTipoCarrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCarreras;
    // End of variables declaration//GEN-END:variables
}
