
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.corredores.vista;

import aplicacion.corredores.controlador.GestionAplicacion;
import aplicacion.corredores.modelo.Carrera;
import aplicacion.corredores.modelo.CorredorParaCarrera;
import aplicacion.corredores.vista.tableModels.TableModelCorredorCarrera;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 * @author migue
 */
public class JDCreacionCarrera extends javax.swing.JDialog {

    private GestionAplicacion gestion;
    private Carrera carrera = null;
    // Variables declaration - do not modify                     
    private com.lavantech.gui.comp.DateTimePicker dateTimePickerFecha;
    private javax.swing.JButton jBContinuar;
    private javax.swing.JButton jBLimpiarCampos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBorrarCorredores;
    private javax.swing.JButton jButtonComenzarCarrera;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLLugar;
    private javax.swing.JLabel jLMaxParticipantes;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTituloFormulario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFMaxParticipantes;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTLugar;
    private javax.swing.JTable jTableCorredoresCarrera;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;

    /**
     * Creates new form JDCreacionCarrera
     *
     * @param parent
     * @param modal
     * @param gestion
     */
    public JDCreacionCarrera(java.awt.Dialog parent, boolean modal, GestionAplicacion gestion) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.gestion = gestion;
        jBContinuar.setEnabled(false);
        registrarValidador();
        jTableCorredoresCarrera.setEnabled(false);
        jButton1.setEnabled(false);
        jButtonBorrarCorredores.setEnabled(false);
        jButtonComenzarCarrera.setEnabled(false);
    }

    JDCreacionCarrera(java.awt.Dialog parent, boolean modal, GestionAplicacion gestion, Carrera carreraSeleccionada) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.gestion = gestion;
        this.carrera = carreraSeleccionada;
        jTLugar.setText(carrera.getLugar());
        jTFMaxParticipantes.setText(String.valueOf(carrera.getMaxCorredores()));
        jTFNombre.setText(carrera.getNombre());
        dateTimePickerFecha.setDate(carrera.getFecha());
        if (carrera.isFinalizada() == true) {
            jTFMaxParticipantes.setEnabled(false);
            jTFNombre.setEnabled(false);
            jTLugar.setEnabled(false);
            dateTimePickerFecha.setEnabled(false);
        }
        pintarTabla();
        registrarValidador();
    }

    private void registrarValidador() {
        ValidationGroup group = validationPanel1.getValidationGroup();
        group.add(jTFNombre, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTLugar, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTFMaxParticipantes, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_VALID_INTEGER);

        validationPanel1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (validationPanel1.getProblem() == null) {
                    jBContinuar.setEnabled(true);
                } else {
                    jBContinuar.setEnabled(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLMaxParticipantes = new javax.swing.JLabel();
        jTFMaxParticipantes = new javax.swing.JTextField();
        jBLimpiarCampos = new javax.swing.JButton();
        jLTituloFormulario = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jBContinuar = new javax.swing.JButton();
        jLLugar = new javax.swing.JLabel();
        jTLugar = new javax.swing.JTextField();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        dateTimePickerFecha = new com.lavantech.gui.comp.DateTimePicker();
        jButtonComenzarCarrera = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorredoresCarrera = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonBorrarCorredores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creacion / modificacion carrera");

        jLMaxParticipantes.setText("Max. Particupantes");

        jTFMaxParticipantes.setName("Max. participantes"); // NOI18N

        jBLimpiarCampos.setText("Limpiar Campos");
        jBLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarCamposActionPerformed(evt);
            }
        });

        jLTituloFormulario.setText("Formulario  Carrera");

        jLFecha.setText("Fecha evento : ");

        jTFNombre.setName("Nombre"); // NOI18N

        jLNombre.setText("Nombre :");

        jBContinuar.setText("Continuar");
        jBContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinuarActionPerformed(evt);
            }
        });

        jLLugar.setText("Lugar");

        jTLugar.setName("Lugar"); // NOI18N

        jButtonComenzarCarrera.setText("Comenzar Carrera");
        jButtonComenzarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComenzarCarreraActionPerformed(evt);
            }
        });

        jTableCorredoresCarrera.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTableCorredoresCarrera);

        jButton1.setText("Añadir Corredores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonBorrarCorredores.setText("Borrar Corredores");
        jButtonBorrarCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarCorredoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLTituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLNombre)
                                                        .addComponent(jLMaxParticipantes)
                                                        .addComponent(jLLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLFecha))
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTLugar)
                                                        .addComponent(jTFMaxParticipantes)
                                                        .addComponent(jTFNombre)
                                                        .addComponent(dateTimePickerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButtonComenzarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonBorrarCorredores)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBLimpiarCampos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBContinuar)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLTituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLNombre))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLLugar)
                                                        .addComponent(jTLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLMaxParticipantes)
                                                        .addComponent(jTFMaxParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLFecha)
                                                        .addComponent(dateTimePickerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBContinuar)
                                        .addComponent(jBLimpiarCampos)
                                        .addComponent(jButton1)
                                        .addComponent(jButtonComenzarCarrera)
                                        .addComponent(jButtonBorrarCorredores))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarCamposActionPerformed
        limpiarCamposJdialog();
        JOptionPane.showMessageDialog(this, "Se han limpiado los campos de este formulario");
    }//GEN-LAST:event_jBLimpiarCamposActionPerformed

    private void jBContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinuarActionPerformed

        String nombre = jTFNombre.getText();
        String lugar = jTLugar.getText();
        Date fecha = dateTimePickerFecha.getDate();
        String maxParticipantes = jTFMaxParticipantes.getText();
        int max = Integer.parseInt(maxParticipantes);
        if (carrera == null) {
            Carrera carreraAux = new Carrera(nombre, fecha, lugar, max);
            gestion.addCarrera(carreraAux);
            JOptionPane.showMessageDialog(this, "Se ha añadido la carrera a la coleccion de carreras");
        } else {
            carrera.setFecha(fecha);
            carrera.setLugar(lugar);
            carrera.setMaxCorredores(max);
            carrera.setNombre(nombre);
        }
        this.dispose();

        //Date fecha = (Date)jSpinnerFecha.getValue();

    }//GEN-LAST:event_jBContinuarActionPerformed

    private void jButtonComenzarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarCarreraActionPerformed
        carrera.setFinalizada(true);
        this.dispose();
    }//GEN-LAST:event_jButtonComenzarCarreraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDSeleccionCorredoresCarrera dialogo = new JDSeleccionCorredoresCarrera(this, true, gestion, carrera);
        dialogo.setVisible(true);
        pintarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBorrarCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarCorredoresActionPerformed
        int[] selectedRows = jTableCorredoresCarrera.getSelectedRows();
        ArrayList<CorredorParaCarrera> corredores = carrera.getCorredores();
        ArrayList<CorredorParaCarrera> corredoresParaBorrar = new ArrayList<>();
        if (selectedRows.length > 0) {
            for (int selectedRow : selectedRows) {
                CorredorParaCarrera corredor = corredores.get(selectedRow);
                corredoresParaBorrar.add(corredor);
            }
        }
        for (CorredorParaCarrera corredor : corredoresParaBorrar) {
            carrera.removeCorredor(corredor.getDorsal());
        }
        pintarTabla();
    }//GEN-LAST:event_jButtonBorrarCorredoresActionPerformed

    private void pintarTabla() {
        ArrayList<CorredorParaCarrera> corredores = carrera.getCorredores();
        TableModelCorredorCarrera modelo = new TableModelCorredorCarrera(corredores);
        jTableCorredoresCarrera.setModel(modelo);
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(modelo);
        jTableCorredoresCarrera.setRowSorter(elQueOrdena);

    }
    // End of variables declaration                   

    private void limpiarCamposJdialog() {
        jTLugar.setText("");
        jTFMaxParticipantes.setText("");
        jTFNombre.setText("");
        dateTimePickerFecha.setDate(new Date());
    }
}
