/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.corredores.vista;

import aplicacion.corredores.controlador.GestionAplicacion;
import aplicacion.corredores.modelo.Carrera;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class JDCreacionCarrera extends javax.swing.JDialog {

    private GestionAplicacion gestion;
    private Carrera carrera = null;

    /**
     * Creates new form JDCreacionCarrera
     */
    public JDCreacionCarrera(java.awt.Dialog parent, boolean modal, GestionAplicacion gestion) {
        super(parent, modal);
        initComponents();
        this.gestion = gestion;
    }

    JDCreacionCarrera(java.awt.Dialog parent, boolean modal, GestionAplicacion gestion, Carrera carreraSeleccionada) {
        super(parent, modal);
        initComponents();
        this.gestion = gestion;
        this.carrera = carreraSeleccionada;
        jTLugar.setText(carrera.getLugar());
        jTFMaxParticipantes.setText(String.valueOf(carrera.getMaxCorredores()));
        jTFNombre.setText(carrera.getNombre());
        dateChooser.setDate(carrera.getFecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLMaxParticipantes = new javax.swing.JLabel();
        jTFMaxParticipantes = new javax.swing.JTextField();
        jBLimpiarCampos = new javax.swing.JButton();
        jLTituloFormulario = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jBContinuar = new javax.swing.JButton();
        jLLugar = new javax.swing.JLabel();
        jTLugar = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLMaxParticipantes.setText("Max. Particupantes");

        jBLimpiarCampos.setText("Limpiar Campos");
        jBLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarCamposActionPerformed(evt);
            }
        });

        jLTituloFormulario.setText("Formulario  Carrera");

        jLFecha.setText("Fecha Nacimiento : ");

        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });

        jLNombre.setText("Nombre :");

        jBContinuar.setText("Continuar");
        jBContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinuarActionPerformed(evt);
            }
        });

        jLLugar.setText("Lugar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBLimpiarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBContinuar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNombre)
                                    .addComponent(jLMaxParticipantes)
                                    .addComponent(jLLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTLugar)
                                    .addComponent(jTFMaxParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jTFNombre))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLugar)
                    .addComponent(jTLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMaxParticipantes)
                    .addComponent(jTFMaxParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFecha)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBContinuar)
                    .addComponent(jBLimpiarCampos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarCamposActionPerformed
        limpiarCamposJdialog();
        JOptionPane.showMessageDialog(this, "Se han limpiado los campos de este formulario");
    }//GEN-LAST:event_jBLimpiarCamposActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jBContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinuarActionPerformed

        String nombre = jTFNombre.getText();
        String lugar = jTLugar.getText();
        Date fecha = dateChooser.getDate();
        String maxParticipantes = jTFMaxParticipantes.getText();
        int max = Integer.parseInt(maxParticipantes);
        if (carrera == null) {
            Carrera carreraAux = new Carrera(nombre, fecha, lugar, max);
            gestion.addCarrera(carreraAux);
            JOptionPane.showMessageDialog(this, "Se ha añadido la carrera a la coleccion de carreras");
        }else{
            carrera.setFecha(fecha);
            carrera.setLugar(lugar);
            carrera.setMaxCorredores(max);
            carrera.setNombre(nombre);
        }
        this.dispose();

        //Date fecha = (Date)jSpinnerFecha.getValue();

    }//GEN-LAST:event_jBContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton jBContinuar;
    private javax.swing.JButton jBLimpiarCampos;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLLugar;
    private javax.swing.JLabel jLMaxParticipantes;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTituloFormulario;
    private javax.swing.JTextField jTFMaxParticipantes;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTLugar;
    // End of variables declaration//GEN-END:variables

    private void limpiarCamposJdialog() {
        jTLugar.setText("");
        jTFMaxParticipantes.setText("");
        jTFNombre.setText("");
        dateChooser.setDate(new Date());
    }
}
