/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.corredores.vista;

import aplicacion.corredores.controlador.GestionAplicacion;
import aplicacion.corredores.modelo.Corredor;
import java.util.Date;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 * @author migue
 */
public class jDInscripcionCorredor extends javax.swing.JDialog {

    private GestionAplicacion gestion;
    private Corredor corredorSeleccionado = null;
    // Variables declaration - do not modify                     
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton jBContinuar;
    private javax.swing.JButton jBLimpiarCampos;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLTituloFormulario;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFDni;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    /**
     * @param parent
     * @param modal
     * @param gestionParametro
     */
    public jDInscripcionCorredor(java.awt.Dialog parent, boolean modal, GestionAplicacion gestionParametro) {
        super(parent, modal);
        this.gestion = gestionParametro;
        initComponents();
        this.setLocationRelativeTo(null);
        jBContinuar.setEnabled(false);
        registrarValidador();
    }
    /**
     * Contructor para modificar
     *
     * @param parent
     * @param modal
     * @param gestionParametro
     * @param corredorSeleccionadoParametro
     */
    public jDInscripcionCorredor(java.awt.Dialog parent, boolean modal, GestionAplicacion gestionParametro, Corredor corredorSeleccionadoParametro) {
        super(parent, modal);
        this.gestion = gestionParametro;
        initComponents();
        this.corredorSeleccionado = corredorSeleccionadoParametro;
        jTFNombre.setText(corredorSeleccionado.getNombre());
        jTFDireccion.setText(corredorSeleccionado.getDireccion());
        jTFDni.setText(corredorSeleccionado.getDni());
        jTFTelefono.setText(String.valueOf(corredorSeleccionado.getTelefono()));
        dateChooser.setDate(corredorSeleccionado.getFechaNacimiento());
        registrarValidador();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBContinuar = new javax.swing.JButton();
        jTFDni = new javax.swing.JTextField();
        jLDireccion = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLTelefono = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jBLimpiarCampos = new javax.swing.JButton();
        jLTituloFormulario = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jLDni = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inscripcion / modificacion corredor");

        jBContinuar.setText("Continuar");
        jBContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinuarActionPerformed(evt);
            }
        });

        jTFDni.setName("Dni"); // NOI18N

        jLDireccion.setText("Direccion :");

        jTFDireccion.setName("Direccion"); // NOI18N

        jLTelefono.setText("Telefono Contacto :");

        jTFTelefono.setName("Telefono"); // NOI18N

        jBLimpiarCampos.setText("Limpiar Campos");
        jBLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarCamposActionPerformed(evt);
            }
        });

        jLTituloFormulario.setText("Formulario Alta Corredor");

        jLFecha.setText("Fecha Nacimiento : ");

        jTFNombre.setName("Nombre"); // NOI18N

        jLNombre.setText("Nombre :");

        jLDni.setText("Dni");

        dateChooser.setDateFormatString("dd/MMM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jBLimpiarCampos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jBContinuar))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLTituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLNombre)
                                                                        .addComponent(jLDireccion)
                                                                        .addComponent(jLFecha)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(jLDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jLTelefono, javax.swing.GroupLayout.Alignment.LEADING)))
                                                                .addGap(38, 38, 38)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jTFDni)
                                                                        .addComponent(jTFDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                                        .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jTFTelefono)
                                                                        .addComponent(jTFNombre)))
                                                        .addComponent(validationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLTituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLNombre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLDni)
                                        .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLDireccion)
                                        .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLTelefono)
                                        .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLFecha)
                                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBContinuar)
                                        .addComponent(jBLimpiarCampos))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinuarActionPerformed

        String nombre = jTFNombre.getText();
        String dni = jTFDni.getText();
        Date fechaNacimiento = dateChooser.getDate();
        String direccion = jTFDireccion.getText();
        String telefonoStr = jTFTelefono.getText();
        int telefono = Integer.parseInt(telefonoStr);

        if (corredorSeleccionado == null) {
            Corredor corredorAux = new Corredor(nombre, dni, fechaNacimiento, direccion, telefono);
            gestion.addCorredorr(corredorAux);
            JOptionPane.showMessageDialog(this, "Se ha añadido el corredor a la coleccion de corredores");
        } else {
            corredorSeleccionado.setNombre(nombre);
            corredorSeleccionado.setDni(dni);
            corredorSeleccionado.setDireccion(direccion);
            corredorSeleccionado.setTelefono(telefono);
            corredorSeleccionado.setFechaNacimiento(fechaNacimiento);
        }
        this.dispose();

        //Date fecha = (Date)jSpinnerFecha.getValue();

    }//GEN-LAST:event_jBContinuarActionPerformed

    private void jBLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarCamposActionPerformed
        limpiarCamposJdialog();
        JOptionPane.showMessageDialog(this, "Se han limpiado los campos de este formulario");
    }//GEN-LAST:event_jBLimpiarCamposActionPerformed

    private void limpiarCamposJdialog() {
        jTFNombre.setText("");
        jTFDireccion.setText("");
        jTFDni.setText("");
        jTFTelefono.setText("");
        dateChooser.setDate(new Date());
    }
    // End of variables declaration                   

    private void registrarValidador() {
        ValidationGroup group = validationPanel1.getValidationGroup();
        group.add(jTFNombre, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTFDireccion, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTFDni, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTFTelefono, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_VALID_INTEGER);

        validationPanel1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (validationPanel1.getProblem() == null) {
                    jBContinuar.setEnabled(true);
                } else {
                    jBContinuar.setEnabled(false);
                }
            }
        });
    }
}
