/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.corredores.vista;

import aplicacion.corredores.controlador.GestionAplicacion;
import aplicacion.corredores.modelo.Carrera;
import aplicacion.corredores.modelo.Corredor;
import aplicacion.corredores.vista.tableModels.TableModelCorredores;

import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.util.ArrayList;
import java.util.Date;

/**
 * @author Miguel
 */
public class JDSeleccionCorredoresCarrera extends javax.swing.JDialog {

    private GestionAplicacion gestion;
    private Carrera carrera;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCorredoresToCarrera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCorredores;

    public JDSeleccionCorredoresCarrera(java.awt.Dialog parent, boolean modal, GestionAplicacion gestion, Carrera carrera) {
        super(parent, modal);
        this.gestion = gestion;
        this.carrera = carrera;
        initComponents();
        this.setLocationRelativeTo(null);
        pintarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jButtonAddCorredoresToCarrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTableCorredores);

        jButtonAddCorredoresToCarrera.setText(org.openide.util.NbBundle.getMessage(JDSeleccionCorredoresCarrera.class, "JDSeleccionCorredoresCarrera.jButtonAddCorredoresToCarrera.text")); // NOI18N
        jButtonAddCorredoresToCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCorredoresToCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonAddCorredoresToCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonAddCorredoresToCarrera)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddCorredoresToCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCorredoresToCarreraActionPerformed
        int[] selectedRows = jTableCorredores.getSelectedRows();
        ArrayList<Corredor> corredores = gestion.getCorredores();
        if (selectedRows.length > 0) {
            for (int selectedRow : selectedRows) {
                Corredor corredor = corredores.get(selectedRow);
                String nombre = corredor.getNombre();
                String dni = corredor.getDni();
                Date fechaNacimiento = corredor.getFechaNacimiento();
                String direccion = corredor.getDireccion();
                int telefono = corredor.getTelefono();
                carrera.addCorredorCarrera(nombre, dni, fechaNacimiento, direccion, telefono);
            }
        }

        this.dispose();
    }//GEN-LAST:event_jButtonAddCorredoresToCarreraActionPerformed

    private void pintarTabla() {
        ArrayList<Corredor> listCorredors = gestion.getCorredores();
        TableModelCorredores modelo = new TableModelCorredores(listCorredors);
        jTableCorredores.setModel(modelo);
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(modelo);
        jTableCorredores.setRowSorter(elQueOrdena);
    }
    // End of variables declaration//GEN-END:variables
}
