/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.corredores.vista;

import aplicacion.corredores.controlador.GestionCorredores;
import aplicacion.corredores.modelo.Corredor;
import aplicacion.corredores.vista.tableModels.TableModelCorredores;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private GestionCorredores gestion = new GestionCorredores();

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPantallaPrincipal = new javax.swing.JPanel();
        jLabelTituloAplicacion = new javax.swing.JLabel();
        jButtonGestionCorredores = new javax.swing.JButton();
        jButtonGestionCarreras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Alta Corredor");
        setMaximumSize(new java.awt.Dimension(21474836, 21474836));
        setMinimumSize(new java.awt.Dimension(500, 300));

        jPPantallaPrincipal.setToolTipText("");
        jPPantallaPrincipal.setMaximumSize(new java.awt.Dimension(3276, 3276));

        jLabelTituloAplicacion.setFont(new java.awt.Font("Dialog", 2, 36)); // NOI18N
        jLabelTituloAplicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloAplicacion.setText("Aplicacion para gestionar corredores y carreras");

        jButtonGestionCorredores.setText("Gestionar Corredores");
        jButtonGestionCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionCorredoresActionPerformed(evt);
            }
        });

        jButtonGestionCarreras.setText("Gestionar Carreras");

        javax.swing.GroupLayout jPPantallaPrincipalLayout = new javax.swing.GroupLayout(jPPantallaPrincipal);
        jPPantallaPrincipal.setLayout(jPPantallaPrincipalLayout);
        jPPantallaPrincipalLayout.setHorizontalGroup(
            jPPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPantallaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloAplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPantallaPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGestionCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPPantallaPrincipalLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jButtonGestionCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(821, Short.MAX_VALUE)))
        );
        jPPantallaPrincipalLayout.setVerticalGroup(
            jPPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPantallaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGestionCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(jPPantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPPantallaPrincipalLayout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jButtonGestionCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionCorredoresActionPerformed
        jDCorredores dialogCorredores = new jDCorredores(this, rootPaneCheckingEnabled, gestion);
        dialogCorredores.setVisible(true);
    }//GEN-LAST:event_jButtonGestionCorredoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionCarreras;
    private javax.swing.JButton jButtonGestionCorredores;
    private javax.swing.JLabel jLabelTituloAplicacion;
    private javax.swing.JPanel jPPantallaPrincipal;
    // End of variables declaration//GEN-END:variables

    /* private void pintarTablaCorredores() {
        ArrayList<Corredor> corredores = gestion.getCorredores();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombre");
        model.addColumn("DNI");
        model.addColumn("Fecha Nacimiento");
        model.addColumn("Direccion");
        model.addColumn("Numero Telefono");
        for (int i = 0; i < corredores.size(); i++) {
            String nombre = corredores.get(i).getNombre();
            String dni = corredores.get(i).getDni();
            String fecha = sdf.format(corredores.get(i).getFechaNacimiento());
            String direccion = corredores.get(i).getDireccion();
            int telefono = corredores.get(i).getTelefono();

            Object[] datosCorredor = {nombre, dni, fecha, direccion, telefono};

            model.addRow(datosCorredor);
        }
        jTableCorredores.setModel(model);
    }*/
}
